.TH nemo-folder-preview-gui 1 "September 2026" "version 0.1.0" "NEMO FOLDER PREVIEW"
.SH NAME
nemo-folder-preview-gui \- configure Nemo Folder Preview
.SH SYNOPSIS
.B nemo-folder-preview-gui
.SH DESCRIPTION
Configure photo-folder previews, Mint-Y folder themes, interface appearance and
language for Nemo Folder Preview.
.SH SEE ALSO
.BR nemo-folder-preview (1)
.SH COPYRIGHT
Nemo Folder Preview is a fork of Cover Thumbnailer. Original copyright ©
2009-2026 Fabien Loison. Fork modifications © 2026 Lucas Gustavo Quiroga.
.SH LICENSE
GNU General Public License, version 3 or later.
