.TH nemo-folder-preview 1 "September 2026" "version 0.1.0" "NEMO FOLDER PREVIEW"
.SH NAME
nemo-folder-preview \- generate photo-folder previews for Nemo
.SH SYNOPSIS
.B nemo-folder-preview
.I input-directory output-thumbnail
.SH DESCRIPTION
Nemo Folder Preview generates a thumbnail showing one to four photos inside a
Mint-Y folder icon for Linux Mint Cinnamon and the Nemo file manager.
.SH SEE ALSO
.BR nemo-folder-preview-gui (1)
.SH COPYRIGHT
Nemo Folder Preview is a fork of Cover Thumbnailer. Original copyright ©
2009-2026 Fabien Loison. Fork modifications © 2026 Lucas Gustavo Quiroga.
.SH LICENSE
GNU General Public License, version 3 or later.
